version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: circleci/postgres:11.1
        environment:
          POSTGRES_USER: 'test_user'
          POSTGRES_DB: 'tpot_programs_integration'
          POSTGRES_PASSWORD: 'test_password'

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "Pipfile.lock" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run:
          name: Install Build Dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install --dev

      # - save_cache:
      #     key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      #     paths:
      #       - ".venv"
      #       - "/usr/local/bin"
      #       - "/usr/local/lib/python3.7/site-packages"


      - run:
          name: Set Appliction Environment to Integration
          command: |
            echo 'export APP_ENV="INTEGRATION"' >> $BASH_ENV

      - run:
          name: Run Tests
          command: |
            ls
            pipenv run pocha tests --reporter xunit

      - store_artifacts:
          path: test-reports
          destination: test-reports
