version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: circleci/postgres:11.1
        environment:
          POSTGRES_USER: 'tpot_programs_test'
          POSTGRES_DB: 'test_user'
          POSTGRES_PASSWORD: 'test_password'

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install --dev
            export APP_ENV=INTEGRATION

      - run:
          name: run tests
          command: |
            pipenv run pocha tests

      - store_artifacts:
          path: test-reports
          destination: test-reports
